version: '3.8'

services:
  mysql:
    image: mysql:latest
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_1
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
      MYSQL_TCP_PORT: 3307
    ports:
      - '3307:3307'
    expose:
      - 3307
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
    networks:
      - weather-network

  redis:
    image: redis:latest  # Use the latest Redis image from Docker Hub

    volumes:
      - redis_data:/data  # Persist Redis data
    ports:
      - "6379:6379"  # Map port 6379 on the host to port 6379 on the container
    networks:
      - weather-network

  weather:
    build:
      context: .
      dockerfile: Dockerfile
#      command: python main.py
#    command: pipenv run uvicorn main:app --reload
    command: python main.py
    volumes:
      - ./:/webapp
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - weather-network

volumes:
  mysql:
  redis_data:

networks:
  weather-network:
